

const itemSeeds = [
    {
        item: "Badia Cinnamon Sticks Mexican",
        price: 3.4,
        category: "spice",
        store: "La Michoacana Meat Market",
        address: "5902 N Shepherd Dr, Houston, TX 77091",
        phone: "713-694-8649",
        lat: 0,
        long: 0,
    },
    {
        item: "Badia Cinnamon Sticks Mexican",
        price: 4.5,
        category: "spice",
        store: "La Michoacana Meat Market",
        address: "0937 FM 1960, Houston, TX 77070",
        phone: "281-807-0981",
        lat: 0,
        long: 0,
    },
    {
        item: "Badia Cinnamon Sticks Mexican",
        price: 5.6,
        category: "spice",
        store: "La Michoacana Meat Market",
        address: "11655 Veterans Memorial Dr, Houston, TX 77067",
        phone: "281-893-0694",
        lat: 0,
        long: 0,
    },
    {
        item: "El Yucateco Paste Achiote",
        price: 8,
        category: "spice",
        store: "La Michoacana Meat Market",
        address: "1002 Boundary St, Houston, TX 77009",
        phone: "713-223-3837",
        lat: 0,
        long: 0,
    },
    {
        item: "El Yucateco Paste Achiote",
        price: 9,
        category: "spice",
        store: "La Michoacana Meat Market",
        address: "3012 Hillcroft St, Houston, TX 77057",
        phone: "281-974-2632",
        lat: 0,
        long: 0,
    },
    {
        item: "El Yucateco green habanero",
        price: 3.4,
        category: "condiment",
        store: "La Michoacana Meat Market",
        address: "5902 N Shepherd Dr, Houston, TX 77091",
        phone: "713-694-8649",
        lat: 0,
        long: 0,
    },
    {
        item: "El Yucateco green habanero",
        price: 4.5,
        category: "condiment",
        store: "La Michoacana Meat Market",
        address: "0937 FM 1960, Houston, TX 77070",
        phone: "281-807-0981",
        lat: 0,
        long: 0,
    },
    {
        item: "El Yucateco green habanero",
        price: 5.6,
        category: "condiment",
        store: "La Michoacana Meat Market",
        address: "11655 Veterans Memorial Dr, Houston, TX 77067",
        phone: "281-893-0694",
        lat: 0,
        long: 0,
    },
    {
        item: "El Yucateco green habanero",
        price: 8,
        category: "condiment",
        store: "La Michoacana Meat Market",
        address: "1002 Boundary St, Houston, TX 77009",
        phone: "713-223-3837",
        lat: 0,
        long: 0,
    },
    {
        item: "El Yucateco green habanero",
        price: 9,
        category: "condiment",
        store: "La Michoacana Meat Market",
        address: "3012 Hillcroft St, Houston, TX 77057",
        phone: "281-974-2632",
        lat: 0,
        long: 0,
    }
];

export default itemSeeds;